### ISSUE TITLE
Fatal Error: Content not allowed in Prolog

### ISSUE THREAD

**Issue by AkshayChordiya** [bonnyfone/vectalign-samples#1]
Hi @bonnyfone 

Thank you for this amazing and damn useful tool. But when I'm trying to use this tool from files it says `Fatal Error: Content not allowed in Prolog`.
The path is generated. And when used it creates a slight problem in the end state icon. 
Well, the main issue is the above error.

**Comment by bonnyfone** [comment]
Hi @AkshayChordiya, thanks for the feedback.
`Fatal Error: Content not allowed in Prolog` is just a warning which may be displayed while checking if the file provided is a valid SVG file or if it is just a txt, so you can just ignore it.

**Comment by AkshayChordiya** [comment]
@bonnyfone 
Thank you. I'm sorry for creating issues at 2 different places.
